# File: pipelines/test.jobs.yml

jobs:
- job: TestsJob
  displayName: 'Test Mollie libraries'
  container: msbuildcontainer
  steps:
    - task: DotNetCoreCLI@2
      displayName: 'Mollie Test'
      inputs:
        command: test
        projects: 'tests\Mollie.Tests\Mollie.Tests.csproj'
        arguments: '-c $(BuildConfiguration)'